server:
  port: 8082
spring:
  application:
    name: booking-service
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://54.210.130.67:8761/eureka


hotel:
  getHotelsByCityUrl: ${GET_HOTELS_BY_CITY_URL:http://100.25.203.57:8083/api/v1/hotel/city/##CITY##}

room:
  getRoomsByPaxCountAndHotelIds: ${GET_ROOMS:http://18.235.248.198:8084/api/v1/room/hotel/pax-count/##PAX_COUNT##/no-of-days/##NO_OF_DAYS##}

logging:
  level:
    com.hilltop: ${LOG_LEVEL:DEBUG}
  file:
    path: ${LOGPATH:/home/ubuntu/logs}
