server:
  port: 8082
spring:
  application:
    name: booking-service

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


hotel:
  getHotelsByCityUrl: ${GET_HOTELS_BY_CITY_URL:http://localhost:8083/api/v1/hotel/city/##CITY##}

room:
  getRoomsByPaxCountAndHotelIds: ${GET_ROOMS:http://localhost:8084/api/v1/room/hotel/pax-count/##PAX_COUNT##/no-of-days/##NO_OF_DAYS##}